<?php

namespace Louvre\TicketingBundle\Repository;

/**
 * BilletRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BilletRepository extends \Doctrine\ORM\EntityRepository
{

	public function nReservation($visitDay)
	{

		$qb = $this->createQueryBuilder('b');

		$qb
			->where('b.visitDay = :visitDay')
			->setParameter('visitDay', $visitDay);
		$nReservation = $qb->getQuery()->getScalarResult();

		return count($nReservation);
	}
}
