home:
    path:     /
    defaults: {_controller: LouvreTicketingBundle:Ticketing:index}

booking:
    path:     /booking
    defaults: {_controller: LouvreTicketingBundle:Ticketing:booking}

booking_prepare:
    path:     /booking/prepare
    defaults: {_controller: LouvreTicketingBundle:Ticketing:prepare}

informations:
    path:     /informations-pratiques
    defaults: {_controller: LouvreTicketingBundle:Ticketing:informations}