services:
  louvre_ticketing.price:
        class: Louvre\TicketingBundle\Services\LouvrePrice
        arguments:
          - %normalPrice%
          - %childrenPrice%
          - %seniorPrice%
          - %reducePrice%

  louvre_ticketing.hourBillet:
      class: Louvre\TicketingBundle\Services\LouvreHourBillet
      arguments: ["@request_stack"]

  louvre_ticketing.quotaMax:
      class: Louvre\TicketingBundle\Services\LouvreQuotaMax

#    louvre_ticketing.example:
#        class: Louvre\TicketingBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
