services:
  louvre_ticketing.price:
        class: Louvre\TicketingBundle\Services\LouvrePrice
        arguments:
          - '%normalPrice%'
          - '%childrenPrice%'
          - '%seniorPrice%'
          - '%reducePrice%'
          - '%childrenAge%'
          - '%normalAge%'
          - '%seniorAge%'

  louvre_ticketing.hourBillet:
      class: Louvre\TicketingBundle\Services\LouvreHourBillet
      arguments: ["@request_stack"]

  louvre_ticketing.quotaMax:
      class: Louvre\TicketingBundle\Services\LouvreQuotaMax
      arguments: 
        - "@request_stack" 
        - "@doctrine.orm.entity_manager"
        - '%quotaMax%'

  louvre_ticketing.stripe:
      class: Louvre\TicketingBundle\Services\Stripe

  louvre_ticketing.codeReservation:
      class: Louvre\TicketingBundle\Services\LouvreCodeReservation
      arguments:
        - "@doctrine.orm.entity_manager"

  louvre_ticketing.booking:
      class: Louvre\TicketingBundle\Services\BookingAction
      arguments:
        - "@louvre_ticketing.hourBillet"
        - "@louvre_ticketing.quotaMax"
        - "@louvre_ticketing.price"

  louvre_ticketing.checkout:
      class:  Louvre\TicketingBundle\Services\CheckoutAction
      arguments:
        - "@louvre_ticketing.stripe"
        - "@louvre_ticketing.codeReservation"
        - "@doctrine.orm.entity_manager"
        - "@twig"
        - "@mailer"


#    louvre_ticketing.example:
#        class: Louvre\TicketingBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
