services:
  louvre_ticketing.price:
        class: Louvre\TicketingBundle\Services\LouvrePrice
        arguments:
          - %normalPrice%
          - %childrenPrice%
          - %seniorPrice%
          - %reducePrice%
#    louvre_ticketing.example:
#        class: Louvre\TicketingBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
